### ISSUE TITLE
Is there a way to implement failover if a primary server does not accept the request?

### ISSUE THREAD

**Issue by MostHated** [mageddo/dns-proxy-server#5] opened 2016-09-22 18:11 UTC
Hello,
    I was wondering if there was a way to have multiple A records for a domain, and then if it detects that the first proxy IP is down, it can then failover and send the request to the second A record IP in the records file?

Thanks!

**Comment by mageddo** [comment] 2016-09-22 18:40
@MostHated If I understand you question you want to have many `A` records at `records.json` file.

I don't know if you have tested it but In fact this is possible and should be working (as I saw at the code). Because when the browser (or whatever) receive a `A` record list then it try one by one looking for a working record

It happen at the `response.answer.push(dns[record.type](record));` instruction in **resolveDnsLocally** function

If it is not working please let me know and if possible create a pull request fixing it :)

**Comment by MostHated** [comment] 2016-09-23 00:27
I will definitely have a go at it tomorrow and let you know, thank you much for the info!

**Comment by mageddo** [comment] 2016-09-23 01:40
You are welcome

**Comment by MostHated** [comment] 2016-09-23 12:58
The best way to test I suppose would be to put in 2 A records, with the first one working and the second working but at a different IP, then take the first IP, make sure it is not working, then it should still work because it ends up going to the second one automatically?

**Comment by mageddo** [comment] 2016-09-23 13:26
Of course, I think that is.  Anyway if you are using linux you can use `nslookup` command to find what `A` records was returned from the DNS Server, something like bellow:

```
$ nslookup stackoverflow.com 
Server:		172.24.0.3
Address:	172.24.0.3#53

Non-authoritative answer:
Name:	stackoverflow.com
Address: 151.101.1.69
Name:	stackoverflow.com
Address: 151.101.193.69
Name:	stackoverflow.com
Address: 151.101.65.69
Name:	stackoverflow.com
Address: 151.101.129.69

```

or specifying what DNS Server you want to use

```
$ nslookup stackoverflow.com 172.24.0.3
```

**Comment by MostHated** [comment] 2016-09-23 15:47
When I do both dig and nslookup for it, I get

`Server:         8.8.8.8
Address:        8.8.8.8#53

Non-authoritative answer:
Name:   mysite.com
Address: 1.1.1.1
`
but, when I go to actually type the address in the browser, I never see the hit reach  my server of 1.1.1.1, it seems to never leave the DNS box, to hit my web hosting box.

**Comment by mageddo** [comment] 2016-09-23 17:12
Ok.. Are you checking the logs? They say that  **dig** is asking **dns-proxy-server** ? Are you running from docker or with npm?

Looks like **dig** is not resolving from **dns-proxy-server** because his say that have used ` 8.8.8.8`.

if you runned it from **npm** make sure that your `/etc/resolv.conf` have something like that:

```
nameserver 127.0.0.1 
```
Also make sure that you are running `npm start` as sudo.

Any way I think that your **records.json** need to looks like that

```
[
	{
		"records": [
			{
				"type": "A",
				"address": "1.1.1.1",
				"ttl": 300,
				"name": "mysite.com"
			},
			{
	        	"type": "A",
				"address": "1.1.1.2",
				"ttl": 300,
				"name": "mysite.com"
			}
		],
		"domain": "mysite.com"
	}
]
```

**Comment by MostHated** [comment] 2016-09-26 14:37
I am using npm, I was doing the command "dig mysite.com @127.0.0.1", I made sure to change my nameserver to 127.0.0.1 as well

**Comment by mageddo** [comment] 2016-09-26 21:24
Anyway it is not working?

**Comment by mageddo** [comment] 2016-09-26 22:19
If not please describe your problem as below, then I will test it and mark as bug and try to solves.
I know that is boring to describe but is good to make sure that we are talking about the same thing .

The functionality with problem: 
Expected behavior: 
Currently behavior:
How simulate this scenario?:
Evidences: (print/output)

**Closed** 2016-09-29 00:17 UTC
Labels: question

**Comment by MostHated** [comment] 2016-09-29 18:13
Sorry about this, I have been quite busy with work the last few days. I will try to get this information over to you as soon as I can!

Thanks for the assistance.

**Comment by mageddo** [comment] 2016-09-29 21:45
No problem guy, ask as you need.
