### ISSUE TITLE
nslookup works but not ping

### ISSUE THREAD

**Issue by kundeng** [mageddo/dns-proxy-server#163] opened 2019-10-05 01:03 UTC
On a linux (mint) system,  I tried it. 
 nslookup works, but ping doesn't.  Any idea why? 

ping dns-proxy-server
ping: dns-proxy-server: Name or service not known

nslookup dns-proxy-server
Server:		172.17.0.2
Address:	172.17.0.2#53

Non-authoritative answer:
*** Can't find dns-proxy-server.localdomain: No answer

I read somewhere I need to remove mdns4.  Do I have to?

**Comment by mageddo** [comment] 2019-11-03 12:16
* Please describe the steps to reproduce the issue including the steps to start DPS.
* Provide which DPS version you're using

**Comment by adigourdi** [comment] 2019-11-14 14:01
Encountered the same issue when my hostnames ended with `.local`
(eg: `alpine.local`, `postgres.local`)

Changed it to `.test` and now it works correctly

Not idea why though

_PS: using :latest docker images_

**Comment by thomasleveil** [comment] 2019-12-31 14:12
domains ending with `.local` are resolved using [mDNS](https://en.wikipedia.org/wiki/Bonjour_(software)) on Linux Mint OS. It's kind of a pain to disable it. The best option is to never use domains ending with ".local" unless you want to actually use mdns.

**Comment by mageddo** [comment] 2020-01-08 11:57
I confirm it, by some reason `.local` domains are not pingable, not sure if I have `mDNS` running, @thomasleveil how can I check that?

linux: Ubuntu 19.04

**Comment by mageddo** [comment] 2020-01-08 12:04
While using ping DPS couldn't solve `.local` DNS names. It is not founding the hostname locally, then proxying to the internet.

```
2020/01/08 12:02:36.998074 INFO f=remote.go:64 pkg=github.com/mageddo/dns-proxy-server/proxy.remoteDnsSolver m=Solve uuid=510c06d8f3 status=bad-code, name=local., rcode=3, err=status=invalid-answer-name, name=local., rcode=3
2020/01/08 12:02:36.998119 INFO f=remote.go:64 pkg=github.com/mageddo/dns-proxy-server/proxy.remoteDnsSolver m=Solve uuid=510c06d8f3 status=complete, name=local., res=3
```

**Comment by mageddo** [comment] 2020-01-08 12:05
I'll have to make deeper fin, looks like DPS it's only receiving the domain, not the full hostname 

`status=complete, name=local., res=3`

**Comment by thomasleveil** [comment] 2020-01-08 12:16
@mageddo : execute `grep hosts: /etc/nsswitch.conf` and see if `mdns` appears

**Comment by mageddo** [comment] 2020-01-08 13:34
> @mageddo : execute `grep hosts: /etc/nsswitch.conf` and see if `mdns` appears

Yes, it appears

```hosts:          files mdns4_minimal [NOTFOUND=return] dns myhostname```

**Comment by mageddo** [comment] 2020-01-15 03:04
When hostnames are terminated by `.local`  ping decides to make a [SOA][1] request to `.local` domain first, it's proxied to **remote** dns server, obviously it's not a valid domain then the **remote** answers **NXDOMAIN** (not found), then **ping** receives it as an error and abort the process, `Name or service not known` is printed by **ping**

[1]: https://en.wikipedia.org/wiki/SOA_record

**Comment by mageddo** [comment] 2020-01-15 03:24
I imagine the **SOA** request is made to check if DPS can solve the hostname after **mdns** fails. Not sure if this check if made by **ping** or **mdns** though.

**Comment by mageddo** [comment] 2020-01-15 03:33
I suppose this issue will be fixed by implementing **SOA** record queries on DPS, actually DPS doesn't fully support it.

**Comment by lucassardois** [comment] 2021-09-03 08:46
I have the same issue except I'm not using `.local`.
I started dps with the following:
```bash
docker run --rm --hostname dns.mageddo \
-v /var/run/docker.sock:/var/run/docker.sock \
-v /etc/resolv.conf:/etc/resolv.conf \
defreitas/dns-proxy-server
```

And as the documentation show, I except to be able to ping `dns.mageddo`, ping returns:
```bash
ping: dns.mageddo: Name or service not known
```

When I do `nslookup dns.magddo` I get:
```bash
Server:         172.17.0.2
Address:        172.17.0.2#53

** server can't find dns.magddo: NXDOMAIN
```

I'm on a Fedora system. When I check the `/etc/resolvconf` whil dps is running I can see the following:
```bash
# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).
# Do not edit.
#
# This file might be symlinked as /etc/resolv.conf. If you're looking at
# /etc/resolv.conf and seeing this text, you have followed the symlink.
#
# This is a dynamic resolv.conf file for connecting local clients to the
# internal DNS stub resolver of systemd-resolved. This file lists all
# configured search domains.
#
# Run "resolvectl status" to see details about the uplink DNS servers
# currently in use.
#
# Third party programs should typically not access this file directly, but only
# through the symlink at /etc/resolv.conf. To manage man:resolv.conf(5) in a
# different way, replace this symlink by a static file or a different symlink.
#
# See man:systemd-resolved.service(8) for details about the supported modes of
# operation for /etc/resolv.conf.

# nameserver 127.0.0.53 # dps-comment
options edns0 trust-ad
search .
nameserver 172.17.0.2 # dps-entry
```

This looks OK to me?

But, when I run `resolvectl status` to check my dns config as explained in the previous file comments:
```bash
Global
         Protocols: LLMNR=resolve -mDNS -DNSOverTLS DNSSEC=no/unsupported
  resolv.conf mode: stub
Current DNS Server: 8.8.8.8
       DNS Servers: 8.8.8.8 8.8.4.4 80.80.80.80

Link 2 (enp0s31f6)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 3 (wlp3s0)
    Current Scopes: DNS LLMNR/IPv4 LLMNR/IPv6
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: fd0f:ee:b0::1
       DNS Servers: 192.168.1.254 fd0f:ee:b0::1

Link 4 (virbr0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 5 (docker0)
Current Scopes: LLMNR/IPv4 LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 6 (br-d1c080aa5d4a)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 7 (br-d32bfd4019c2)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 8 (br-7dbacfc74479)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported

Link 14 (veth42c3216)
Current Scopes: LLMNR/IPv6
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
```

Where `wlp3s0` is my wifi interface currently used.

Any idea on how to fix this issue?

**Comment by mageddo** [comment] 2023-03-04 16:54
So, just to give an conclusion to this issue, there is no much to do about `.local` entries, they are entries for a [reserved domain](https://en.wikipedia.org/wiki/.local), just don't use that if you want to not have issues, because Linux won't forward .local hostname queries to the configured DNS, if you query using nslookup or whatever client specifying DPS server then it will work.


```bash
$ docker run --rm -it --hostname dns-proxy-server.local alpine sh
$ docker run --rm -it --hostname dns-proxy-server.dev alpine sh
```

```
# Querying letting the system decide whether use DNS server or not won't work.
$ nslookup dns-proxy-server.local
Server:		127.0.0.53
Address:	127.0.0.53#53

** server can't find dns-proxy-server.local: SERVFAIL

# .dev domain works normally
$ nslookup dns-proxy-server.dev
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
Name:	dns-proxy-server.dev
Address: 172.17.0.5

# Query .local domain specifying DPS server will work though
$ nslookup -po=8053 dns-proxy-server.local 127.0.0.1
Server:		127.0.0.1
Address:	127.0.0.1#8053

Non-authoritative answer:
Name:	dns-proxy-server.local
Address: 172.17.0.4
Name:	dns-proxy-server.local
Address: 172.17.0.4

```

**Comment by mageddo** [comment] 2023-03-04 16:58
@lucassardois  I think your issue has a different  cause, maybe it's related wit this entry `search .` you could try remove it, maybe it's related to system-resolved in that case you can see [this thread](https://github.com/mageddo/dns-proxy-server/issues/244), if neither don't solve your issues then you can open a new issue , please.

**Closed by mageddo** 2023-03-04 16:58 UTC
Labels: confirmed
