### ISSUE TITLE
Does dps support reverse DNS?

### ISSUE THREAD

**Issue by qianhd** [mageddo/dns-proxy-server#233] opened 2021-11-01 08:54 UTC
### What is expected

Does dps support reverse DNS?

### What is Happening

I found that when i using container's hostname ping container on host，it's alway wait some time. i do some research, the reason is reverse DNS timeout.

**Comment by mageddo** [comment] 2023-03-02 16:53
Hey, localdb and docker  entries doesn't have [reverse dns support][1], I don't know much about this feature by haven't sure if it would solve your problem. So you are trying to ping a container from their hostname from the host machine, right? Something like (haven't tested this exact code snippet):

```bash
$ docker run --rm --hostname nginx.dev nginx
$ ping nginx.dev
```

And the ping is not working? As the given example it should work and ping normally, if you aren't able to, it can be because you ran the container using an overlay network, take a look at [this section][2], it may explain the issue you are getting.


[1]: https://en.wikipedia.org/wiki/Reverse_DNS_lookup
[2]: http://mageddo.github.io/dns-proxy-server/latest/en/2-features/dps-network-resolution/#why-it-is-necessary

**Comment by rissson** [comment] 2023-03-08 10:57
I should be possible to answer a `1.1.16.172.in-addr.arpa.	IN	PTR` query by looking up if there is a container with the IP `172.16.1.1`, and otherwise returning a NXDOMAIN. It would be quite useful to have!

###### Love the project btw, thanks a lot!

**Comment by mageddo** [comment] 2023-03-19 14:09
Hey @rissson,  I agree it can be useful, but I'm afraid it won't solve @qianhd question, so I've created #378 for the reverse DNS implementation and closing this one as we haven't a conclusive root cause here, feel free to reopen it and complement your question if you need it.

**Closed by mageddo** 2023-03-19 14:09 UTC
Labels: question
