### ISSUE TITLE
Does not work when using on OSX

### ISSUE THREAD

**Issue by XaeroDegreaz** [mageddo/dns-proxy-server#44] opened 2017-10-14 12:35 UTC
The `resolv.conf` is not used for DNS resolution on OSX.

```
#
# Mac OS X Notice
#
# This file is not used by the host name and address resolution
# or the DNS query routing mechanisms used by most processes on
# this Mac OS X system.
#
# This file is automatically generated.
#
search domain.com
nameserver 0.0.0.5
nameserver 0.0.0.6
nameserver 192.168.1.1
```

I haven't found a way to get this working :(

Edit: nevermind -- The requirements on the readme show linux.

**Comment by mageddo** [comment] 2017-10-14 14:17
@XaeroDegreaz Yep, it was designed to work with linux, anyway I think that's totally possible to get it working with OSX, I think DNS Proxy Server just don't know how to set as your default DNS, the main problem is that I have not a MAC, if you are interested we can work the it working.

### Give a try
Run it using docker
```bash
docker run --hostname dns.mageddo --name dns-proxy-server \
-v /var/run/docker.sock:/var/run/docker.sock \
defreitas/dns-proxy-server
```
Let's see if it is working
```bash
$ nslookup google.com `docker inspect dns-proxy-server --format '{{.NetworkSettings.IPAddress}}'`
Server:		172.17.0.4
Address:	172.17.0.4#53

Non-authoritative answer:
Name:	google.com
Address: 172.217.29.206
```
If it is ok, now let's set is as your default DNS, [this answer](https://serverfault.com/a/478542) says that you can do it simply putting the DNS server IP in Network Settings, you can get the DNS Server IP by running the follow command:

```bash
docker inspect dns-proxy-server --format '{{.NetworkSettings.IPAddress}}'
```
If it works please let me know, maybe DNS Server already works for MAC :) .

**Comment by lbustelo** [comment] 2017-11-09 03:04
Did it work?

**Comment by XaeroDegreaz** [comment] 2017-11-09 04:43
When I tried initially, I already set the DNS to the address of the proxy server, but it didn't work. However, I think it may have been because I was on my company's VPN which kind of locks down all DNS modification. It may work off of the VPN, but I haven't actually tried. Sorry, the project I was working on I ended up resolving my issue another way.

**Comment by ortizfabio** [comment] 2018-02-01 02:26
I had the same problem and luckily I saw this post:
I have a mac
 16.7.0 Darwin Kernel Version 
I run the command above and the result  is shown below. However the script hang up and I had to send a CTL-C to ended. My purpose was for the host to be able to reach the docker containers. I have to containers install and running including this dns. Now when I ping from each other I get a response. But from the host I get nothing. Printing the routing table show no entry for the docker machines which have addresses at: 172.17.0.2 and 172.17.0.3(dns). Any help getting this dns working so that I can access the docker machines from the host would be appreciated.


################## Routing table ##################
USSYFSTMM217142:Downloads 502489430$ netstat -rn
Routing tables

Internet:
Destination        Gateway            Flags        Refs      Use   Netif Expire
default            192.168.0.1        UGSc          136       25     en0
127                127.0.0.1          UCS             0        0     lo0
127.0.0.1          127.0.0.1          UH              2     2878     lo0
169.254            link#4             UCS             0        0     en0
192.168.0          link#4             UCS             2        0     en0
192.168.0.1/32     link#4             UCS             1        0     en0
192.168.0.1        c4:e9:84:f0:bf:47  UHLWIir       145      550     en0   1192
192.168.0.2        c:47:c9:4b:3b:ab   UHLWI           0       10     en0   1069
192.168.0.4        7c:8b:ca:1f:31:f7  UHLWIi          1        0     en0   1156
192.168.0.5/32     link#4             UCS             0        0     en0
224.0.0/4          link#4             UmCS            2        0     en0
224.0.0.251        1:0:5e:0:0:fb      UHmLWI          0        0     en0
239.255.255.250    1:0:5e:7f:ff:fa    UHmLWI          0       88     en0
255.255.255.255/32 link#4             UCS             0        0     en0

Internet6:
Destination                             Gateway                         Flags         Netif Expire
default                                 fe80::%utun0                    UGcI          utun0
::1                                     ::1                             UHL             lo0
fe80::%lo0/64                           fe80::1%lo0                     UcI             lo0
fe80::1%lo0                             link#1                          UHLI            lo0
fe80::%en0/64                           link#4                          UCI             en0
fe80::c84:86ad:442e:c2a0%en0            30:35:ad:c7:6c:80               UHLI            lo0
fe80::%awdl0/64                         link#8                          UCI           awdl0
fe80::2c11:5ff:fede:c017%awdl0          2e:11:5:de:c0:17                UHLI            lo0
fe80::%utun0/64                         fe80::4c92:3fdf:5a77:60c4%utun0 UcI           utun0
fe80::4c92:3fdf:5a77:60c4%utun0         link#9                          UHLI            lo0
ff01::%lo0/32                           ::1                             UmCI            lo0
ff01::%en0/32                           link#4                          UmCI            en0
ff01::%awdl0/32                         link#8                          UmCI          awdl0
ff01::%utun0/32                         fe80::4c92:3fdf:5a77:60c4%utun0 UmCI          utun0
ff02::%lo0/32                           ::1                             UmCI            lo0
ff02::%en0/32                           link#4                          UmCI            en0
ff02::%awdl0/32                         link#8                          UmCI          awdl0
ff02::%utun0/32                         fe80::4c92:3fdf:5a77:60c4%utun0 UmCI          utun0
USSYFSTMM217142:Downloads 502489430$ 


################# Output of host ifconfig #################
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
	options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
	inet 127.0.0.1 netmask 0xff000000 
	inet6 ::1 prefixlen 128 
	inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1 
	nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 30:35:ad:c7:6c:80 
	inet6 fe80::c84:86ad:442e:c2a0%en0 prefixlen 64 secured scopeid 0x4 
	inet 192.168.0.5 netmask 0xffffff00 broadcast 192.168.0.255
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
en1: flags=963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX> mtu 1500
	options=60<TSO4,TSO6>
	ether 9a:00:10:90:d9:60 
	media: autoselect <full-duplex>
	status: inactive
bridge0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=63<RXCSUM,TXCSUM,TSO4,TSO6>
	ether 9a:00:10:90:d9:60 
	Configuration:
		id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
		maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
		root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
		ipfilter disabled flags 0x2
	member: en1 flags=3<LEARNING,DISCOVER>
	        ifmaxaddr 0 port 5 priority 0 path cost 0
	nd6 options=201<PERFORMNUD,DAD>
	media: <unknown type>
	status: inactive
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
	ether 02:35:ad:c7:6c:80 
	media: autoselect
	status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
	ether 2e:11:05:de:c0:17 
	inet6 fe80::2c11:5ff:fede:c017%awdl0 prefixlen 64 scopeid 0x8 
	nd6 options=201<PERFORMNUD,DAD>
	media: autoselect
	status: active
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
	inet6 fe80::4c92:3fdf:5a77:60c4%utun0 prefixlen 64 scopeid 0x9 
	nd6 options=201<PERFORMNUD,DAD>

############## Output of docker run #######################
18-02-01 02:00:13.556 INF id=1, m=GetCurrentPath currentPath=/app
18-02-01 02:00:13.556 DEB id=1, m=MapReq status=mapping, url=GET /v1/caches
18-02-01 02:00:13.557 DEB id=1, m=MapReq status=mapping, url=GET /v1/caches/size
18-02-01 02:00:13.557 DEB id=1, m=MapReq status=mapping, url=GET /env/active
18-02-01 02:00:13.557 DEB id=1, m=MapReq status=mapping, url=PUT /env/active
18-02-01 02:00:13.558 DEB id=1, m=MapReq status=mapping, url=GET /env/
18-02-01 02:00:13.558 DEB id=1, m=MapReq status=mapping, url=POST /env/
18-02-01 02:00:13.558 DEB id=1, m=MapReq status=mapping, url=DELETE /env/
18-02-01 02:00:13.558 DEB id=1, m=MapReq status=mapping, url=GET /hostname/
18-02-01 02:00:13.559 DEB id=1, m=MapReq status=mapping, url=GET /hostname/find/
18-02-01 02:00:13.559 DEB id=1, m=MapReq status=mapping, url=POST /hostname/
18-02-01 02:00:13.559 DEB id=1, m=MapReq status=mapping, url=PUT /hostname/
18-02-01 02:00:13.559 DEB id=1, m=MapReq status=mapping, url=DELETE /hostname/
18-02-01 02:00:13.559 DEB id=1, m=MapReq status=mapping, url=GET /
18-02-01 02:00:13.560 DEB id=1, m=MapReq status=mapping, url=GET /configuration/
18-02-01 02:00:13.560 INF id=2, m=LoadConfiguration status=begin, confPath=/app/conf/config.json
18-02-01 02:00:13.560 INF id=2, m=LoadConfiguration status=create-new-conf
18-02-01 02:00:13.561 DEB id=2, m=SaveConfiguration status=begin
18-02-01 02:00:13.561 DEB id=2, m=SaveConfiguration status=save
18-02-01 02:00:13.561 INF id=2, m=SaveConfiguration status=success, time=0
18-02-01 02:00:13.561 INF id=2, m=LoadConfiguration status=success
18-02-01 02:00:13.562 INF id=2, m=main status=listing-signals
18-02-01 02:00:13.562 INF id=2, m=goexit status=setup-requests
18-02-01 02:00:13.562 INF id=3, m=LoadConfiguration status=begin, confPath=/app/conf/config.json
18-02-01 02:00:13.562 INF id=3, m=LoadConfiguration status=openingFile
18-02-01 02:00:13.562 INF id=3, m=LoadConfiguration status=success
18-02-01 02:00:13.562 INF id=2, m=goexit status=setResolvconf
18-02-01 02:00:13.562 INF id=1, m=SetCurrentDNSServerToMachine status=begin, ip=172.17.0.3, err=<nil>
18-02-01 02:00:13.562 INF id=1, m=ProcessResolvconf status=begin
18-02-01 02:00:13.562 INF id=1, m=ProcessResolvconf status=open-conf-file, file=/etc/resolv.conf
18-02-01 02:00:13.562 DEB id=1, m=ProcessResolvconf status=readline, line=# Generated by dhcpcd from eth0.dhcp, type=COMMENT
18-02-01 02:00:13.562 DEB id=1, m=ProcessResolvconf status=readline, line=# /etc/resolv.conf.head can replace this line, type=COMMENT
18-02-01 02:00:13.562 DEB id=1, m=ProcessResolvconf status=readline, line=search adsyf.syfbank.com app.syfbank.com cpu.syfbank.com gdn.syfbank.com, type=ELSE
18-02-01 02:00:13.563 DEB id=1, m=ProcessResolvconf status=readline, line=nameserver 192.168.65.1, type=SERVER
18-02-01 02:00:13.563 DEB id=1, m=ProcessResolvconf status=readline, line=# /etc/resolv.conf.tail can replace this line, type=COMMENT
18-02-01 02:00:13.563 INF id=1, m=ProcessResolvconf status=success, buffLength=276
18-02-01 02:00:13.566 INF id=5, m=LoadConfiguration status=begin, confPath=/app/conf/config.json
18-02-01 02:00:13.567 INF id=5, m=LoadConfiguration status=openingFile
18-02-01 02:00:13.567 INF id=5, m=LoadConfiguration status=success
18-02-01 02:00:13.568 INF id=8, m=LoadConfiguration status=begin, confPath=/app/conf/config.json
18-02-01 02:00:13.568 INF id=8, m=LoadConfiguration status=openingFile
18-02-01 02:00:13.569 INF id=4, m=HandleDockerEvents serverVersion={Version:17.12.0-ce APIVersion:1.35 GitCommit:c97c6d6 GoVersion:go1.9.2 Os:linux Arch:amd64 KernelVersion:4.9.60-linuxkit-aufs Experimental:true BuildTime:2017-12-27T20:12:29.000000000+00:00}, err=<nil>
18-02-01 02:00:13.569 INF id=8, m=LoadConfiguration status=success
18-02-01 02:00:13.571 DEB id=2, m=serve status=begin, port=53
18-02-01 02:00:13.572 INF id=7, m=LoadConfiguration status=begin, confPath=/app/conf/config.json
18-02-01 02:00:13.573 INF id=7, m=LoadConfiguration status=openingFile
18-02-01 02:00:13.573 INF id=7, m=LoadConfiguration status=success
18-02-01 02:00:13.573 INF id=2, m=goexit status=web-server-starting, port=5380
18-02-01 02:00:13.572 INF id=6, m=LoadConfiguration status=begin, confPath=/app/conf/config.json
18-02-01 02:00:13.575 INF id=6, m=LoadConfiguration status=openingFile
18-02-01 02:00:13.576 INF id=6, m=LoadConfiguration status=success
18-02-01 02:00:13.578 INF id=4, m=HandleDockerEvents status=container-from-list-begin, container=/demo2.6.3
18-02-01 02:00:13.579 DEB id=4, m=putHostnames host=sandbox-hdp.hortonworks.com, ip=172.17.0.2
18-02-01 02:00:13.580 INF id=4, m=HandleDockerEvents status=container-from-list-success, container=/demo2.6.3, hostnames=[sandbox-hdp.hortonworks.com]
18-02-01 02:00:13.581 INF id=9, m=LoadConfiguration status=begin, confPath=/app/conf/config.json
18-02-01 02:00:13.582 INF id=9, m=LoadConfiguration status=openingFile
18-02-01 02:00:13.583 INF id=9, m=LoadConfiguration status=success
18-02-01 02:00:13.583 DEB id=2, m=serve status=begin, port=53
18-02-01 02:00:13.588 INF id=10, m=HandleDockerEvents status=resolved-hosts, action=start, hostnames=[dns.mageddo]
18-02-01 02:00:13.589 DEB id=10, m=putHostnames host=dns.mageddo, ip=172.17.0.3# dps-entry, type=PROXY
18-02-01 02:05:39.607 INF id=1, m=ProcessResolvconf status=success, buffLength=226
18-02-01 02:05:39.607 INF id=1, m=RestoreResolvconfToDefault status=success, err=<nil>
18-02-01 02:05:39.607 WAR id=2, m=main status=exiting, signal=interrupt

**Comment by mageddo** [comment] 2018-02-01 12:54
Thanks for your feedback, let's try to solve it.

> I run the command above and the result is shown below. However the script hang up and I had to send a CTL-C to ended.

Run the script bellow and hang the terminal is a expected behavior, if you want to run it in background please use docker  `-d` option
```
docker run --hostname dns.mageddo --name dns-proxy-server \
-v /var/run/docker.sock:/var/run/docker.sock \
defreitas/dns-proxy-server
```

> Now when I ping from each other I get a response. But from the host I get nothing

That's why DNS-PROXY-SERVER is not your default dns server because I don't know how to do that in OSX, then we must to set it as default manually. We need to find out how to set dns-proxy-server as the default dns. Looking at the logs, it registered the containers as expected

Can you try run nslookup (you can also use dig) to solve the hostnames from host and give me the output? See that the command bellow will for to use dns-proxy-server as the DNS but just to this command, this way we can see if dns-proxy-server is working internally
```
$ nslookup sandbox-hdp.hortonworks.com `docker inspect dns-proxy-server --format '{{.NetworkSettings.IPAddress}}'`
```

**Comment by BR0kEN-** [comment] 2018-03-18 22:07
What I did to try getting it working:

```
docker inspect dns-proxy-server --format '{{.NetworkSettings.IPAddress}}'
172.17.0.4
```

<img width="697" alt="monosnap 2018-03-19 00-04-03" src="https://user-images.githubusercontent.com/2760616/37571740-3c759a86-2b09-11e8-83dc-30e9b84bb931.png">

But unfortunately got nothing:

```
nslookup test-project.loc
;; connection timed out; no servers could be reached
```

```
nslookup google.com `docker inspect dns-proxy-server --format '{{.NetworkSettings.IPAddress}}'`
;; connection timed out; no servers could be reached
```

@mageddo, did I do something incorrectly?

**Comment by mageddo** [comment] 2018-03-19 03:55
@BR0kEN- 
> The underlying issue, I believe, is within "Docker for mac" that uses VM.

I think you're right, I am doing some tests to get it work using docker for Windows and I think the issue is the same, no news because it`s not possible to use docker inside a VM, but now I have a Windows installation then I will try to fix it and probably the same aproach will work for MAC

**Comment by haffonist** [comment] 2018-06-04 11:54
Was this ever solved ?

**Comment by Aloren** [comment] 2018-06-07 12:40
Unfortunately that doesn't work :(
I've executed almost the same steps as @BR0kEN- did, but that didn't help. 
```
asmirnova:~ asmirnova$ networksetup -getdnsservers Wi-Fi
127.0.0.1
asmirnova:~ asmirnova$ nslookup couchbase
Server:		127.0.0.1
Address:	127.0.0.1#53

** server can't find couchbase: NXDOMAIN
```

**Comment by Kearny** [comment] 2020-01-24 13:17
Hello everyone,

Is there any news on this ? Im experiencing some issues with my Mac while with this while it works perfectly fine on another Ubuntu machine.

**Comment by mageddo** [comment] 2020-01-24 13:19
@Kearny  I'm about to use a Mac of a friend of mine to make the tests.

I'll keep this thread updated

**Comment by Kearny** [comment] 2020-01-28 08:59
Hello @mageddo, any news on this ?
I'm working in a project that requires this. I confess I can't make it work on my own... 😩

**Comment by mageddo** [comment] 2020-01-30 00:45
@Kearny I made some tests, I have some good and not so good news.

Basically DPS works on Mac, the configuration is pretty similar as Windows, I will make a doc for that soon.

Unfortunately access container from host is not supported yet, it's a [docker machine limitation](https://docs.docker.com/docker-for-mac/networking/)    . I'm thinking in a working around for this.

All other features are working perfectly, like:

* Local entries
* Remote proxy 


Which DPS feature are you interested to work on Mac?

**Comment by Kearny** [comment] 2020-01-30 08:34
Hi @mageddo,

First, thanks for your time and interest.

I'm interested in being able to access different containers from my host.
I have the same name dns behind which I have one service per port.
Example: 
- dns.name:27017 --> mongodb container
- dns.name:80 --> web app container
- dns.name:3306 --> mysql database container

And all the containers are able to talk to each others.

**Comment by mageddo** [comment] 2020-01-30 12:18
I see, Containers solve each other are supposed to work,

**Comment by mageddo** [comment] 2020-01-30 12:20
I see, Containers solve each others are supposed to work, I think additional configuration will be required.

Host solve containers works but host have no ACL to ping containers cause Mac don't have a bridge network like Linux.

**Comment by Swoorup** [comment] 2020-03-28 12:31
FYI, docker acknowledges that they don't support IP routing in mac. 
https://docs.docker.com/docker-for-mac/networking/

There appears to be 3rd party component in the last post of this thread which might address the issue.
https://forums.docker.com/t/ip-routing-to-container/8424/15

I might give that a try and let know if it works

**Comment by Swoorup** [comment] 2020-03-28 13:03
@mageddo @Kearny  I got it to successfully work using the mentioned tool in that post. Steps are below:

1. Clone the repository: https://github.com/AlmirKadric-Published/docker-tuntap-osx
1. Install tuntap using `brew cask install tuntap`
1. Run this command from the repository: 
   1. `/sbin/docker_tap_install.sh`
   1. `./sbin/docker_tap_up.sh`
1. Add the route to docker network via the tap ip address. 
`sudo route add -net 172.0.0.0 -netmask 255.255.0.0 10.0.75.2`
1. Setup the dns server to `172.0.0.10` in your mac.

**Comment by Kearny** [comment] 2020-03-30 11:50
@mageddo @Swoorup Here we changed our solution by using TRAEFIK instead : https://docs.traefik.io/routing/providers/docker/

It work perfectly on MAC by default.

**Comment by Swoorup** [comment] 2020-04-10 15:50
@Kearny I looked at Traefik, it seems a bit too heavyweight for my needs. Currently running everything just locally and just need something that proxies off all ports including tcp with minimal configuration.

**Comment by MonniSoftware** [comment] 2020-04-25 20:36
> @mageddo @Kearny I got it to successfully work using the mentioned tool in that post. Steps are below:
> 
> 1. Clone the repository: https://github.com/AlmirKadric-Published/docker-tuntap-osx
> 2. Install tuntap using `brew cask install tuntap`
> 3. Run this command from the repository:
>    
>    1. `/sbin/docker_tap_install.sh`
>    2. `./sbin/docker_tap_up.sh`
> 4. Add the route to docker network via the tap ip address.
>    `sudo route add -net 172.0.0.0 -netmask 255.255.0.0 10.0.75.2`
> 5. Setup the dns server to `172.0.0.10` in your mac.

Hello, 
thanks for very interesting workaround for OSX. I got this pretty much working according to logs that I can see, only what's not working is the last point, setting Mac's DNS server to 172.0.0.10. For example 'nslookup my-ubuntu' does not find IP address, although dns-proxy-server shows in its log, that it has registered that name and it looks it would be ready for resolving that name. 

My question, where does this address 172.0.0.10 come from? How can I check, that that is actually the IP address of the DNS server spawned here?

**Comment by Swoorup** [comment] 2020-04-26 03:15
@MonniSoftware it is the dps server ip address. https://github.com/mageddo/dns-proxy-server/blob/master/examples/custom-hostnames-compose-file/docker-compose.yml#L13

**Comment by mageddo** [comment] 2020-04-27 23:12
> @MonniSoftware it is the dps server ip address. https://github.com/mageddo/dns-proxy-server/blob/master/examples/custom-hostnames-compose-file/docker-compose.yml#L13

You always can use `docker inspect dns-proxy-server | less` and find out the container IP by yourself though

**Comment by gchari-asapp** [comment] 2020-08-04 20:44
@Swoorup solution is partially running for me now. The main problem I have is that I have no way of passing the hostname to DPS. It always use as hostname the container id:
```
020/08/04 20:32:51.588867 INFO f=docker.go:104 pkg=github.com/mageddo/dns-proxy-server/events/docker m=HandleDockerEvents uuid=2516591d2f status=resolved-hosts, action=stop, hostnames=[57a305043286]
2020/08/04 20:32:51.589878 INFO f=docker.go:104 pkg=github.com/mageddo/dns-proxy-server/events/docker m=HandleDockerEvents uuid=7fd3dd67d7 status=resolved-hosts, action=stop, hostnames=[a5a644440192]
```

Was anyone able to connect using hostnames?

**Comment by christhomas** [comment] 2020-12-01 20:19
on mac (before big sur), I used to use: 
`sudo networksetup -setdnsservers 'Wi-Fi' 0.0.0.0`

but for some reason it stopped working, so I changed it to: 
`sudo networksetup -setdnsservers 'Wi-Fi' 0.0.0.0 127.001"

and it started working again. I've been using 0.0.0.0 for a couple of years and it's worked without problem up until I upgraded to big sur. It's only in the last month I had to change it. Perhaps the version of MacOS matters, but perhaps not.

**Comment by mageddo** [comment] 2023-03-04 04:14
I'm finally with access to a MacBook so I did some tests using DPS [3.7.0][1], my conclusion is it's now working the best it can on Mac due Docker for Mac limitations, can you confirm that or am I missing some feature? Got the following results after ran the steps below:

```bash
$ sudo ./dns-proxy-server
```

A nginx container: 
```bash
$ docker run --rm --hostname nginx.docker nginx
```

Running a container to make some tests
```bash
$ docker run --rm -it --hostname alpine.docker alpine sh

# Docker gateway is solving 
$ nslookup gateway.docker.internal
Server:   192.168.65.7
Address:  192.168.65.7:53

Non-authoritative answer:
Name: gateway.docker.internal
Address: 192.168.65.2

Non-authoritative answer:

$ nslookup host.docker.internal
Server:   192.168.65.7
Address:  192.168.65.7:53

Non-authoritative answer:

Non-authoritative answer:
Name: host.docker.internal
Address: 192.168.65.2

# DPS docker container feature is also solving
$ nslookup alpine.docker
Server:   192.168.65.7
Address:  192.168.65.7:53

Non-authoritative answer:
Name: alpine.docker
Address: 172.17.0.4

Non-authoritative answer:

# Internet resolution also working
$ nslookup google.com
Server:   192.168.65.7
Address:  192.168.65.7:53

Non-authoritative answer:
Name: google.com
Address: 2800:3f0:4001:833::200e

Non-authoritative answer:
Name: google.com
Address: 142.250.219.238

# Other container also solving 
$ wget -q -S -O - nginx.docker
  HTTP/1.1 200 OK
  Server: nginx/1.23.3
  Date: Sat, 04 Mar 2023 03:50:52 GMT
  Content-Type: text/html
  Content-Length: 615
  Last-Modified: Tue, 13 Dec 2022 15:53:53 GMT
  Connection: close
  ETag: "6398a011-267"
  Accept-Ranges: bytes
```

Checkout [running it docs for Mac][2] (actually nothing special for Mac, just some hints)

[2]: http://mageddo.github.io/dns-proxy-server/latest/en/1-getting-started/running-it/#running-on-mac
[1]: https://github.com/mageddo/dns-proxy-server/releases/download/3.7.0/dns-proxy-server-linux-amd64-3.7.0.tgz

**Comment by mageddo** [comment] 2023-03-16 04:23
Created [a dedicated tutorial][1] for Windows and MacOSX usecase, also created [this section][2] where people can link tutorials they created, feel free to contribute.

I'm closing this issue as I consider it's solved, if you have any new issues or questions feel free to open a new issue, thanks.



[1]: http://mageddo.github.io/dns-proxy-server/latest/en/5-tutorials/docker-reverse-proxy/
[2]: http://mageddo.github.io/dns-proxy-server/latest/en/5-tutorials/

**Closed by mageddo** 2023-03-16 04:23 UTC
Labels: feature
