### ISSUE TITLE
Running dns-proxy-server makes docker image builds fail, with `cannot resolve host` errors

### ISSUE THREAD

**Issue by SimJoSt** [mageddo/dns-proxy-server#251] opened 2022-12-02 09:52 UTC
### What is Happening

* Building docker images with the need to resolve external dependencies throws "cannot resolve host" errors.

### What is expected

Docker image builds are not affected.
Either they resolve normally or through dns-proxy-server

### Steps to Reproduce

1. Have a dns-proxy-server running
2. Start a Docker image build with the need to resolve external dependencies

**Specs:**
- OS: Debian 10 Buster
- Docker Version: 20.10.21
- DPS Version: 2.19.0

**Comment by zxzharmlesszxz** [comment] 2023-02-15 13:06
UP!

**Comment by mageddo** [comment] 2023-02-23 04:16
Hey, I wasn't able to reproduce this behavior, What I noticed is that docker caches the DNS server address, so if you start DPS, restart docker, then restart DPS again and it get a new docker container IP then you can get an issue, because docker cached the previous DPS IP and will try to solve names from an IP that is not DPS server anymore. I think there's no much DPS can do in this case.

Can you please confirm if your usecase is something like that or give more details on the steps to reproduce it?

If your usecase is the mentioned, then you can lead with this by fixing a IP address to the DPS container by using `docker run --ip ... ` .

Thanks in advance.

**Comment by mageddo** [comment] 2023-02-23 04:17
@zxzharmlesszxz @SimJoSt

**Comment by mageddo** [comment] 2023-02-23 05:26
I've noticed that this  can be related to this one  https://github.com/mageddo/dns-proxy-server/issues/248, if DPS use systemd-resolved instead of the resolv.conf file this issue may  disappear

**Comment by SimJoSt** [comment] 2023-02-23 10:14
We don't restart the containers that much on their own, so I don't think thus would be it. Of course it could be possible.
I'll check that out on the next maintenance.
It will take a few days at least to confirm this is fixes the issue.

**Comment by zxzharmlesszxz** [comment] 2023-02-24 04:26
It is possible if you run dns-proxy container at the different network than other containers, example:
- run dns-proxy at dns network
- run test container at the test network
What's happened?
DNS not resolved!
Example 2:
When your dns-proxy container is running at different than default network,
run build container command, what happens:
- DNS-proxy at the different network
- build process running at the default network
Build process doesn't have access to dns-proxy to resolve names

**Comment by mageddo** [comment] 2023-02-25 12:47
Hey @zxzharmlesszxz , it would be easier to understand the scenario with a minimal reproducible example, focusing on your first example, I tried the below but still works

```yml
version: '3'
services:
  dps:
    image: defreitas/dns-proxy-server:2.19.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
    hostname: dns.mageddo
    networks:
      dns:
  nginx:
    image: nginx:1.22
    hostname: nginx.app
    networks:
      test:

networks:
  dns:
  test:

```

```bash
curl -I nginx.app
HTTP/1.1 200 OK
Server: nginx/1.22.1
```

**Comment by mageddo** [comment] 2023-02-25 13:24
Created a [section][1] at the docs to add more details about that.

[1]: http://mageddo.github.io/dns-proxy-server/latest/en/2-features/docker-different-networks-solving/

**Comment by zxzharmlesszxz** [comment] 2023-02-25 18:36
It's really working, but can you to try build other docker image with models and npm install when this docker-compose containers will working.
At this situation - dns resolves will be failed

**Comment by mageddo** [comment] 2023-02-25 18:57
@zxzharmlesszxz Maybe your failing use case is related to this thread? #244 If yes we can migrate this discussion to there

**Comment by mageddo** [comment] 2023-02-28 03:15
The issue #244 was considered fixed, can you test version 3.5.0 and check if your issue persists? If not we can close this one

**Comment by mageddo** [comment] 2023-03-02 16:04
Please re-open it if have any updates

**Closed** 2023-03-02 16:03 UTC
Labels: waiting-feedback, triage

**Comment by SimJoSt** [comment] 2023-07-27 10:26
@mageddo thanks for the debugging, fixing, development and engagement 🙏 

I finally got around to checking all the comments, resources and new releases.
As recommended, I got the binary (https://github.com/mageddo/dns-proxy-server/releases/tag/3.15.13-snapshot) instead of the Docker version. After shutting down the Docker version, confirming that it removed its entries from `/etc/resolve.conf`, I started it with commands mentioned here: https://mageddo.github.io/dns-proxy-server/3.8/en/1-getting-started/running-it/linux/
I could verify it used the `/etc/systemd/resolved.conf` file and changed the necessary entries. However, I could not resolve the docker hostnames like `nextcloud.docker` anymore. Switching back to the preexisting, not-updated Docker version, resolved the issue.

I also tried to install it as a Linux service following the instructions: https://github.com/mageddo/dns-proxy-server/blob/master/docs/content/2-features/installing-as-service/_index.en.md?plain=1#L23
Checking the `--help`, I also tried `-service=normal` instead of `-service=docker` from the docs. None of the registered a service.

Is there anything obvious I might have missed, switching from Docker to binary?
This problem can be moved to a new issue, I just wanted to document the results here, as I have not been able to get it running to test, if the original issue has been resolved.

**Comment by mageddo** [comment] 2023-07-27 15:05
So you are getting issues with to solve docker containers when running the new version, right? Yep, I agree, please open a new issue describing the reproducing steps

**Comment by mageddo** [comment] 2023-07-27 15:05
@SimJoSt

**Comment by SimJoSt** [comment] 2023-07-29 10:29
@mageddo I have done so: https://github.com/mageddo/dns-proxy-server/issues/424
